title: Sarah the Physicicist
description: Science Communicator
author: Sarah Sweeney
email: contact@sarahthephysicicist.com

theme: jekyll-theme-dinky

# Load custom stylesheet
custom_css: _assets/css/custom.css
 
# Pages to show in navigation
nav:
  - title: Home
    url: /
  - title: About
    url: /about

