title: Sarah the Physicicist
description: Physics Communication
author: Sarah Sweeney
email: contact@sarahthephysicicist.com

theme: jekyll-theme-dinky

# Pages to show in navigation
nav:
  - title: Home
    url: /
  - title: About
    url: /about

